### ISSUE TITLE
sample app?

### ISSUE THREAD

**Issue by aloksharma1** [LoaderB0T/ng-dynamic-mf#5]
hello,
it would be nice to have a example app showcasing angular dynamic components in action with your library, something similar to : 
https://github.com/manfredsteyer/module-federation-with-angular-dynamic

showing a shell app and components apps

**Comment by LoaderB0T** [comment]
Hi there.
I mentioned an example in the readme: https://github.com/LoaderB0T/awdware3

**Comment by LoaderB0T** [comment]
Let me know if you have further questions, though! :)

**Comment by aloksharma1** [comment]
> Let me know if you have further questions, though! :)

thanks i will check this tomorrow
